# _base_: 'deeplabv3p_resnet50_os8_cityscapes_1024x512_80k.yml'
batch_size: 4
iters: 4000

train_dataset:
  type: Dataset
  dataset_root: goals_data/Train
  num_classes: 4
  train_path: goals_data/Train/train_0.txt
  val_path: goals_data/Train/val_0.txt
  transforms:
    - type: ResizeStepScaling
      min_scale_factor: 0.75
      max_scale_factor: 2.0
      scale_step_size: 0.25
    - type: RandomPaddingCrop
      crop_size: [800, 600]
    - type: RandomHorizontalFlip
    - type: RandomDistort
      brightness_range: 0.4
      contrast_range: 0.4
      saturation_range: 0.4
    # - type: RandomNoise
    # - type: RandomBlur
    # - type: VerticalShift
    #   max_range: 200
    - type: Normalize
      mean: [0.22619521, 0.22619521, 0.22619521]
      std: [0.16060336, 0.16060336, 0.16060336]
  mode: train

val_dataset:
  type: Dataset
  dataset_root: goals_data/Train
  num_classes: 4
  train_path: goals_data/Train/train_0.txt
  val_path: goals_data/Train/val_0.txt
  transforms:
    - type: Normalize
      mean: [0.22619521, 0.22619521, 0.22619521]
      std: [0.16060336, 0.16060336, 0.16060336]
  mode: val


optimizer:
  type: sgd
  momentum: 0.9
  weight_decay: 4.0e-3

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.01
  end_lr: 0
  power: 0.9

loss:
  types:
    # - type: DiceLoss
    # - type: MixedLoss
    #   losses:
    #     - type: CrossEntropyLoss
    #     - type: DiceLoss
    #   coef: [0.5, 0.5]
    # - type: OhemCrossEntropyLoss
    #   label_smooth: True
      # num_class: 4
    - type: MixedLoss
      losses:
        - type: OhemCrossEntropyLoss
          label_smooth: True
        - type: RelaxBoundaryLoss
      coef: [1, 1]
  coef: [1]

# test_config:
#     is_slide: True
#     crop_size: [800, 800]
#     stride: [600, 600]

model:
  type: DeepLabV3P
  backbone:
    type: ResNet101_vd
    output_stride: 8
    multi_grid: [1, 2, 4]
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/resnet101_vd_ssld.tar.gz
  num_classes: 4
  backbone_indices: [0, 3]
  aspp_ratios: [1, 12, 24, 36]
  aspp_out_channels: 256
  align_corners: False
#   pretrained: /home/aistudio/PaddleSeg/output/deeplabv3p/mae/iter_20000/model.pdparams
