# _base_: 'deeplabv3p_resnet50_os8_cityscapes_1024x512_80k.yml'
batch_size: 8
iters: 4000

train_dataset:
  type: Dataset
  dataset_root: /home/aistudio/goals_data/Train
  num_classes: 4
  train_path: /home/aistudio/goals_data/Train/train_0.txt
  val_path: /home/aistudio/goals_data/Train/val_0.txt
  transforms:
    - type: ResizeStepScaling
      min_scale_factor: 0.75
      max_scale_factor: 2.0
      scale_step_size: 0.25
    - type: RandomPaddingCrop
      crop_size: [800, 600]
    - type: RandomHorizontalFlip
    - type: RandomDistort
      brightness_range: 0.4
      contrast_range: 0.4
      saturation_range: 0.4
    # - type: RandomNoise
    # - type: RandomBlur
    # - type: VerticalShift
    #   max_range: 200
    - type: Normalize
      mean: [0.22619521, 0.22619521, 0.22619521]
      std: [0.16060336, 0.16060336, 0.16060336]
  mode: train

val_dataset:
  type: Dataset
  dataset_root: /home/aistudio/goals_data/Train
  num_classes: 4
  train_path: /home/aistudio/goals_data/Train/train_0.txt
  val_path: /home/aistudio/goals_data/Train/val_0.txt
  transforms:
    - type: Normalize
      mean: [0.22619521, 0.22619521, 0.22619521]
      std: [0.16060336, 0.16060336, 0.16060336]
  mode: val


optimizer:
  type: sgd
  momentum: 0.9
  weight_decay: 4.0e-3

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.01
  end_lr: 0
  power: 0.9


loss:
  types:
    - type: OhemCrossEntropyLoss
    - type: PixelContrastCrossEntropyLoss
      temperature: 0.1
      base_temperature: 0.07
      ignore_index: 255
      max_samples: 1024
      max_views: 100
  coef: [1, 0.1]

model:
  type: HRNetW48Contrast
  backbone:
    type: HRNet_W48
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/hrnet_w48_ssld.tar.gz
  in_channels: 720
  drop_prob: 0.1
  proj_dim: 720


optimizer:
  type: sgd
  weight_decay: 0.0005


lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.01
  end_lr: 0.0
  power: 0.9
